services:
  - type: web
    name: urbanroof-ddr-generator
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 300 --workers 1
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.7

